<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-10T13:07:32 ICT" name="Default suite" finished-at="2024-04-10T13:08:00 ICT" duration-ms="28411">
    <groups>
    </groups>
    <test started-at="2024-04-10T13:07:32 ICT" name="Default test" finished-at="2024-04-10T13:08:00 ICT" duration-ms="28411">
      <class name="Test.XoaKhachHang">
        <test-method is-config="true" signature="beforClass()[pri:0, instance:Test.XoaKhachHang@2f7298b]" started-at="2024-04-10T13:07:32 ICT" name="beforClass" finished-at="2024-04-10T13:07:42 ICT" duration-ms="9807" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforClass -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Test.XoaKhachHang@2f7298b]" started-at="2024-04-10T13:07:42 ICT" name="beforeMethod" finished-at="2024-04-10T13:07:42 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="test1()[pri:1, instance:Test.XoaKhachHang@2f7298b]" started-at="2024-04-10T13:07:42 ICT" name="test1" finished-at="2024-04-10T13:07:53 ICT" duration-ms="11414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Test.XoaKhachHang@2f7298b]" started-at="2024-04-10T13:07:53 ICT" name="afterMethod" finished-at="2024-04-10T13:07:53 ICT" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Test.XoaKhachHang@2f7298b]" started-at="2024-04-10T13:07:53 ICT" name="beforeMethod" finished-at="2024-04-10T13:07:53 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="test2()[pri:2, instance:Test.XoaKhachHang@2f7298b]" started-at="2024-04-10T13:07:53 ICT" name="test2" finished-at="2024-04-10T13:08:00 ICT" duration-ms="7088" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at Test.XoaKhachHang.test2(XoaKhachHang.java:73)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Test.XoaKhachHang@2f7298b]" started-at="2024-04-10T13:08:00 ICT" name="afterMethod" finished-at="2024-04-10T13:08:00 ICT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:Test.XoaKhachHang@2f7298b]" started-at="2024-04-10T13:08:00 ICT" name="afterClass" finished-at="2024-04-10T13:08:00 ICT" duration-ms="33" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Test.XoaKhachHang -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
